package stix21

const AV = "Anti-Virus / Anti-Malware solution"
const CAPEC = "Common Attack Pattern Enumeration and Classification"
const Consumer = "Any entity that receives STIX content"
const CTI = "Cyber Threat Intelligence"
const Deprecated = "STIX features or properties that are in the process of being replaced by newer ones."
const Embedded_Relationship = "A link (an \"edge\" in a graph) between one STIX Object and another represented as a property on one object containing the ID of another object"
const Entity = "Anything that has a separately identifiable existence (e.g., organization, person, group, etc.)"
const IEP = "FIRST (Forum of Incident Response and Security Teams) Information Exchange Policy"
const Instance = "A single occurrence of a STIX Object version"
const MTI = "Mandatory To Implement"
const Object_Creator = "The entity that created or updated a STIX Object (see section 3.5)"
const Object_Representation = "An instance of an object version that is serialized as STIX"
const Producer = "Any entity that distributes STIX content, including object creators as well as those passing along existing content"
const SCO = "STIX Cyber-observable Object"
const SDO = "STIX Domain Object (a \"node\" in a graph)"
const SRO = "STIX Relationship Object (one mechanism to represent an \"edge\" in a graph)"
const STIX = "Structured Threat Information Expression"
const STIX_Content = "STIX documents, including STIX Objects, STIX Objects grouped as bundles, etc."
const STIX_Object = "A STIX Domain Object (SDO), STIX Cyber Observable Object (SCO), STIX Relationship Object (SRO), or STIX Meta Object."
const STIX_Relationship = "A link (an \"edge\" in a graph) between two STIX Objects represented by either an SRO or an embedded relationship"
const TAXII = "An application layer protocol for the communication of cyber threat information"
const TLP = "Traffic Light Protocol"
const TTP = "Tactic, technique, or procedure; behaviors and resources that attackers use to carry out their attacks"